### ISSUE TITLE
fix the ci failure

### ISSUE THREAD

**Issue by parasol-aser** [parasol-aser/JMCR#4]
It appears the continuous integration is broken. @huangshiyou Can you fix it?

**Comment by huangshiyou** [comment]
I think it is OK now.

**Comment by huangshiyou** [comment]
I have no idea how travis ci build the project. I checked some errors reported in the log:
<img width="901" alt="screen shot 2017-11-29 at 3 40 02 pm" src="https://user-images.githubusercontent.com/7650529/33400453-c28e3644-d51b-11e7-90ab-b6dc387e256d.png">
Even though I exclude those files, the errors are still reported by the travis ci. 
I do not think this is a big problem because at least it is built successfully on the local. The changes of the source are applied but just the building failure reported by travis ci. These error exist when the repository is initialized. I think we can just turn off the travis ci.
